project:
  type: website
  output-dir: docs
website:
  navbar:
    title: "GRASS Tutorials"
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
    tools:
      - icon: github
        menu: 
          - text: "Source Code"
            href: "https://github.com/ncsu-geoforall-lab/tutorials"
          - text: "Report an Issue"
            href: "https://github.com/ncsu-geoforall-lab/tutorials/issues"

execute:
  freeze: auto
format:
  html:
    theme: [pandoc, theme.scss]
    toc: true
    toc-title: Table of Contents